Implement essential claims support to OAuth2
wso2-extensions/identity-inbound-auth-oauth pull request #1786
Opened 2022-02-01 07:49 UTC by Nilki

### Proposed changes in this pull request

Implement the code for supporting essential claims and essential claims with value.

2022-02-21 07:39 UTC, senthalan requested changes

2022-02-21 07:39 UTC, senthalan commented on pom.xml
> +                <configuration>
We can't skip checkstyle plugins

2022-02-21 07:39 UTC, senthalan commented on components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultIDTokenBuilder.java
> +import java.util.*;
We don't use * imports

2022-02-21 07:39 UTC, senthalan commented on components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java
> +   /**private static Map<String, String> filterEssentialClaimJson(String essentialClaims, String claimType){
Why do we have this code block commented ?

2022-03-07 06:31 UTC, closed without merging

2022-03-07 06:33 UTC, Nilki commented
Please refer new PR [https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1789]