Introduce OIDC scopes handling to scope validation
wso2-extensions/identity-inbound-auth-oauth pull request #1991
Opened 2022-12-21 18:54 UTC by shashimalcse

### Proposed changes in this pull request

$subject

2022-12-21 19:06 UTC, mefarazath requested changes

2022-12-21 19:06 UTC, mefarazath commented on components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/validators/OIDCScopeHandler.java
>              tokReqMsgCtx.setScope(scopes);
This needs to be remove with the new change right?

2022-12-21 19:06 UTC, mefarazath commented on components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/RefreshGrantHandler.java
> +        List<String> grantedScopeList = Stream.concat(Arrays.stream(grantedScopes),
If we are going to check contains wouldnt it be good to use Set

2022-12-21 19:15 UTC, shashimalcse commented on components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/RefreshGrantHandler.java
> +            if (filteredScopes.isEmpty()) {
if requestedScopes is empty we set scope as an empty array in first place right?

2022-12-22 03:51 UTC, shashimalcse commented on components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/RefreshGrantHandler.java
> +        String[] grantedScopes = tokReqMsgCtx.getScope();
put a comment

2024-11-19 16:16 UTC, closed without merging